name: AlternateAccountFinder
version: '${project.version}'
author: DanTheTechMan
main: dansplugins.detectionsystem.AlternateAccountFinder
api-version: 1.13

commands:
  aaflist:
  aafsearch:

permissions:
  aaf.list:
    default: op
  aaf.search:
    default: op