name: AlternateAccountFinder
version: '${version}'
authors:
- DanTheTechMan
- alyphen
main: com.dansplugins.detectionsystem.AlternateAccountFinder
api-version: 1.17

commands:
  aaf:
    description: |
      Alternate Account Finder commands
      /aaf accounts [ip] - Lists all accounts that have logged in from the specified IP
      /aaf ips [player] - Lists all IPs that the specified player has logged in from
      /aaf alts [player] - Lists the suspected alts of a specified player

permissions:
  aaf.accounts:
    description: Allows the user to view accounts for an IP
    default: op
  aaf.ips:
    description: Allows the user to view IPs for a player
    default: op
  aaf.alts:
    description: Allows the user to view alts for a player
    default: op